#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# 新的42个题目，保持原有格式
questions_text = """          {
            text: "很难集中注意力完成工作、学校作业或其他活动",
            example: "例如：容易分心，难以专注于任务",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难持续关注任务或娱乐活动",
            example: "例如：看书、看电影或听讲座时注意力不集中",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "当别人直接对我说话时，经常似乎没有在听",
            example: "例如：心不在焉，即使没有明显干扰也容易走神",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常不能按照指示完成任务，无法完成工作或学业",
            example: "例如：开始任务但很快失去注意力，容易分心",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难组织任务和活动",
            example: "例如：难以管理连续性任务，难以保持物品整齐，工作混乱",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常回避、不喜欢或不愿参与需要持续精神努力的任务",
            example: "例如：学校作业或家庭作业，准备报告",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常丢失任务或活动所需的物品",
            example: "例如：学校用品、铅笔、书籍、工具、钱包、钥匙、文件",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "容易被外部刺激分散注意力",
            example: "例如：无关的想法或环境中的噪音",
            type: "inattention",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在日常活动中经常健忘",
            example: "例如：忘记做家务、跑腿办事，回复电话或赴约",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常在座位上扭动手脚或感到坐立不安",
            example: "例如：在会议或课堂上感到不舒服",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常在应该坐着的情况下站起来",
            example: "例如：在课堂、办公室或其他需要保持坐姿的场所",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在不适当的情况下经常跑来跑去或感到坐立不安",
            example: "例如：在需要安静的场合感到内心不安",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难安静地参与休闲活动",
            example: "例如：看电影、读书时感到焦躁",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常'忙个不停'或表现得像'被马达驱动'一样",
            example: "例如：无法长时间坐着放松，别人觉得你很焦躁",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常说话过多",
            example: "例如：在社交场合说话太多，垄断对话",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常在问题还没问完就脱口而出答案",
            example: "例如：抢着回答问题，完成别人的句子",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难等待轮到自己",
            example: "例如：排队时不耐烦",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常打断或干扰他人",
            example: "例如：插话或干扰别人的对话、游戏或活动",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难制定现实的长期目标和计划",
            example: "例如：设定不切实际的目标或无法坚持长期计划",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难管理时间和优先级",
            example: "例如：经常迟到，无法准确估计任务所需时间",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难控制情绪和冲动",
            example: "例如：容易发脾气，做决定时不够冷静",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难从过去的错误中学习并调整行为",
            example: "例如：重复犯同样的错误",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难在多个任务间切换和调整策略",
            example: "例如：从一个项目转到另一个项目时感到困难",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难监控和评估自己的表现",
            example: "例如：不知道自己做得怎么样，缺乏自我觉察",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在做重要决定时经常过于冲动",
            example: "例如：换工作、购买昂贵物品或做财务决定时不够仔细考虑",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难抵制即时满足的诱惑",
            example: "例如：明知道应该工作却选择看手机或做其他娱乐活动",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常在不合适的时候表达想法或感受",
            example: "例如：在严肃场合说不合时宜的话",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难在做决定前仔细思考后果",
            example: "例如：不考虑行动可能带来的长期影响",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在压力或情绪激动时更容易做出冲动行为",
            example: "例如：生气时说狠话，兴奋时做危险的事",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难控制网络使用或其他成瘾行为",
            example: "例如：计划只看一会儿手机却看了几小时",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常在购物时做出冲动消费决定",
            example: "例如：买了很多不需要的东西",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在社交媒体上经常发表后来后悔的内容",
            example: "例如：冲动发帖或评论",
            type: "impulsivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难在需要安静时控制身体动作",
            example: "例如：在图书馆、电影院或重要会议中坐立不安",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常感觉需要同时进行多个活动才能满足",
            example: "例如：看电视时必须同时玩手机",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难在睡前让身体和思维都平静下来",
            example: "例如：上床后还是感到精力旺盛，思绪活跃",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常感到内心躁动，即使外表看起来平静",
            example: "例如：内心总有种要动的冲动",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难享受需要安静和放松的活动",
            example: "例如：冥想、按摩或其他放松活动时感到不适",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "在运动或体力活动后很难快速平静下来",
            example: "例如：运动后还是感觉精力充沛，难以休息",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "经常无意识地做重复性动作",
            example: "例如：转笔、敲桌子、抖腿或玩头发",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难在无聊时保持耐心，总想寻找刺激",
            example: "例如：空闲时总想找些事情做，很难什么都不做",
            type: "hyperactivity",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难维持稳定的工作或学习节奏",
            example: "例如：有时效率很高，有时完全无法集中，表现不一致",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },
          {
            text: "很难适应变化和调整计划",
            example: "例如：当计划被打乱时感到极度困扰，难以灵活应对",
            type: "executive",
            options: [
              { text: "从不", value: 0 },
              { text: "很少", value: 1 },
              { text: "有时", value: 2 },
              { text: "经常", value: 3 },
              { text: "总是", value: 4 },
            ],
          },"""

print(questions_text)
